$\text{IMPORTS}$

In [1]:
import cvxpy as cp
import numpy as np

$\textbf{QUESTION 1}$
$$

$$

In [31]:
A1 = np.array([40, 0, 0])
A2 = np.array([0, 16, 0])
A3 = np.array([0, 0, 12])
c_b = np.array([1, 1, 1])

B = np.matrix([A1, A2, A3]).T
inv_b = np.linalg.inv(B)
y_hat = np.array(c_b @ inv_b)
print(f"\nBasis Matrix:\n{B=}\nInverse of Basis Matrix:\n{inv_b=}\n{y_hat=}")
print("\nOptimal Solution:\nx1 = 3.75\nx2 = 6.25\nx3 = 6.67")
print("\nOptimal Value:\n16.67")


Basis Matrix:
B=matrix([[40,  0,  0],
        [ 0, 16,  0],
        [ 0,  0, 12]])
Inverse of Basis Matrix:
inv_b=matrix([[0.025     , 0.        , 0.        ],
        [0.        , 0.0625    , 0.        ],
        [0.        , 0.        , 0.08333333]])
y_hat=array([[0.025     , 0.0625    , 0.08333333]])

Optimal Solution:
x1 = 3.75
x2 = 6.25
x3 = 6.67

Optimal Value:
16.67


$\textbf{QUESTION 2}$
$$

$$

In [32]:
x1 = cp.Variable(1)
x2 = cp.Variable(1)
x3 = cp.Variable(1)

obj = cp.Minimize(x1 + x2 + x3)
constraints = [40 * x1 == 150,
               16 * x2 == 100, 
               12 * x3 == 80,
               x1 >=0,
               x2 >=0,
               x3 >=0]

roll = cp.Problem(obj, constraints)
roll.solve()
print(f"The Optimal Value:\n{roll.value}")

x = np.array([v[0].value for i, v in enumerate([x1, x2, x3])])
print(f"\nOptimal Solution:\n{x=}")

cvx_yhat = np.array([-constraints[i].dual_value[0] for i, v in enumerate(constraints)])
print(f"\nOptimal Dual Solution:\n{cvx_yhat=}")

print(f"\nBasis Matrix:\n{B=}\nInverse of Basis Matrix:\n{inv_b=}")

The Optimal Value:
16.66666666666666

Optimal Solution:
x=array([3.75      , 6.25      , 6.66666667])

Optimal Dual Solution:
cvx_yhat=array([ 2.50000000e-02,  6.25000000e-02,  8.33333333e-02, -6.34729978e-10,
       -4.44359035e-10, -4.00182754e-10])

Basis Matrix:
B=matrix([[40,  0,  0],
        [ 0, 16,  0],
        [ 0,  0, 12]])
Inverse of Basis Matrix:
inv_b=matrix([[0.025     , 0.        , 0.        ],
        [0.        , 0.0625    , 0.        ],
        [0.        , 0.        , 0.08333333]])


$\textbf{QUESTION 3}\\
\text{Write the Knapsack Problem}$

$$
z = max \{0.025a_1 + 0.0625a_2 + 0.0833a_3 \}\\
S.T.\\
5a_1 + 12a_2 + 16a_3 \le 200\\
a_1, a_2, a_3 \ge 0
$$

$\textbf{QUESTION 4}\\
\text{Solve the Knapsack Problem}$

$$
\text{The optimal solution (z):}\ 1.0416 \Rightarrow \\
1-z \lt 0 \Rightarrow \\
\text{Column generation algorithm does not terminate.} \Rightarrow \\
\text{We say the new column to enter:} \ A_4 = [0, 14, 2] \Rightarrow \\~\\
\text{New Pattern (A):}
\begin{bmatrix}
40 & 0 & 0 & 0\\
0 & 16 & 0 & 14\\
0 & 0 & 12 & 2
\end{bmatrix}

$$

In [38]:
a1 = cp.Variable(1, integer=True)
a2 = cp.Variable(1, integer=True)
a3 = cp.Variable(1, integer=True)

expr = (0.025 * a1) + (0.0625 * a2) + (0.0833 * a3)

next_obj = cp.Maximize(expr)
next_constraints = [(5 * a1) + (12 * a2) + (16 * a3) <= 200,
                    a1 >= 0,
                    a2 >= 0,
                    a3 >= 0]

next_roll = cp.Problem(next_obj, next_constraints)
next_roll.solve()
print(f"The Optimal Value:\n{next_roll.value}")

A4 = np.matrix([v[0].value for i, v in enumerate([a1, a2, a3])]).T
print(f"\nOptimal Solution:\n{A4=}")

new_B = np.append(B, A4, axis=1)

print(f"New pattern:\n{new_B}")



The Optimal Value:
1.0416

Optimal Solution:
A4=matrix([[ 0.],
        [14.],
        [ 2.]])
New pattern:
[[40.  0.  0.  0.]
 [ 0. 16.  0. 14.]
 [ 0.  0. 12.  2.]]


$\textbf{QUESTION 5}$

$$

$$

$\textbf{QUESTION 6}$

$$

$$